"""Initial migration

Revision ID: 0f84cb61e2a2
Revises: 
Create Date: 2026-08-07 17:08:37.481830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f84cb61e2a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('donations',
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('food_type', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.String(length=100), nullable=False),
    sa.Column('expiry_time', sa.DateTime(), nullable=False),
    sa.Column('pickup_location', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('donation_id')
    )
    op.create_index(op.f('ix_donations_donation_id'), 'donations', ['donation_id'], unique=False)
    op.create_table('deliveries',
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=True),
    sa.Column('pickup_status', sa.String(length=50), nullable=False),
    sa.Column('delivery_status', sa.String(length=50), nullable=False),
    sa.Column('pickup_time', sa.DateTime(), nullable=True),
    sa.Column('delivery_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.donation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    op.create_index(op.f('ix_deliveries_delivery_id'), 'deliveries', ['delivery_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('ngo_id', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('delivery_risk', sa.String(length=100), nullable=False),
    sa.Column('recommendation_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.donation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ngo_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_index(op.f('ix_recommendations_recommendation_id'), 'recommendations', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_recommendation_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_deliveries_delivery_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_donations_donation_id'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
