"""Add NGOProfile table

Revision ID: a91ef0b22322
Revises: 0f84cb61e2a2
Create Date: 2026-08-07 19:09:43.422678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a91ef0b22322'
down_revision: Union[str, Sequence[str], None] = '0f84cb61e2a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ngo_profiles',
    sa.Column('ngo_profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('accepted_food_type', sa.String(length=255), nullable=False),
    sa.Column('available_volunteers', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ngo_profile_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_ngo_profiles_ngo_profile_id'), 'ngo_profiles', ['ngo_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ngo_profiles_ngo_profile_id'), table_name='ngo_profiles')
    op.drop_table('ngo_profiles')
    # ### end Alembic commands ###
